apiVersion: v1
kind: Service
metadata:
  name: fieldtrack-backend-service
spec:
  selector:
    app: fieldtrack-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
